language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - LIBSTDC_VERSION=6
    - CLANG_VERSION=3.7

matrix:
  allow_failures:
    - os: linux
    - compiler: gcc

before_install:
  # Setup cmake
  - sh scripts/install-cmake.sh

  # Prepare compilers
  - if [[ "$CXX" == "g++" || "$CC" == "gcc" ]]; then sh scripts/install-gcc.sh; fi
  - if [[ "$CXX" == "clang++" || "$CC" == "clang" ]]; then sh scripts/install-clang.sh; fi

  #- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  #- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

install:
  # Before cmake
  - rm -rf build/
  - mkdir build
  - cd build
  - cmake ..

script:
  # Build with cmake
  - make

notifications:
  email: false

sudo: required

cache:
  - apt
